1.It couldn't work because "throw" would immediately terminate the program without doing code below.
2.No.Because the throw 3.0 would be catched by "catch(float)" and jump out of program.

    
